llm_chain:
    platform:
        openai:
            api_key: '%env(OPENAI_API_KEY)%'
    chain:
        default:
            model:
                name: 'GPT'
                version: 'gpt-4o-mini'
            system_prompt: 'You are a pirate and you write funny.'
